---
application:
  name: "dungeongram"
  project: "dungeongram"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "dungeongram"
  version: "4.4"
routers:
- name: "main-dungeongram"
  routes:
  - application_name: "dungeongram"
    paths:
    - "/*"
