---
application:
  name: "dungeongram"
  project: "DungeonGram"
  organization: "QoveryCommunity"
routers:
- name: "main-dungeongram"
  custom_domains:
  - branch: master
    domain: www.dungeongram.com
  routes:
  - application_name: "dungeongram"
    paths:
    - "/*"
